services:
  db:
    image: postgres:16
    container_name: test_db
    env_file:
      - .env-non-dev
    ports:
      - "5433:5432"

  test:
    image: test_image
    build:
      context: .
    container_name: test_app
    env_file:
      - .env-non-dev
    depends_on:
      - db  
    command: > #чтобы избежать добавления миграционных файлов
      sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "7777:8000" 
