# Generated by Django 5.1.5 on 2025-01-28 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_modem_counter_modem_id_alter_modem_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='timestamp',
        ),
    ]
